name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Label PR based on files changed
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Label PR
        uses: ./
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
